service: HuskyFit-API
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 'lambda:InvokeFunction'
    Resource: "*"

plugins:
  - serverless-offline
  - serverless-add-api-key
  - serverless-plugin-warmup

custom:
  apiKeys:
    - name: noah-api-key

  warmup:
    default:
      enabled: true
      folderName: '.warmup'
      memorySize: 256
      name: warmer-default
      events:
        - schedule: 'cron(0/5 13-5 ? * SUN-SAT *)' # 8:00am to 12:00pm EST | Every 5 minutes | UTX
      package:                                     
        individually: true
        patterns:
          - '!../**'
          - '!../../**'
          - ./**
      timeout: 5
      concurrency: 1

functions:
  getMeals:
    runtime: python3.9
    handler: scraper.lambda_handler
    timeout: 10 # lambda will timeout after 10 secs

    # Disable warmup
    warmup:
      default:
        enabled: true

    events:
      - http:
          path: /{dininghall}/{meal}
          method: get
          private: true